#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : dnf-plugins-core
Version  : 4.0.21
Release  : 35
URL      : https://github.com/rpm-software-management/dnf-plugins-core/archive/refs/tags/4.0.21.tar.gz
Source0  : https://github.com/rpm-software-management/dnf-plugins-core/archive/refs/tags/4.0.21.tar.gz
Summary  : Core Plugins for DNF
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: dnf-plugins-core-libexec = %{version}-%{release}
Requires: dnf-plugins-core-locales = %{version}-%{release}
Requires: dnf-plugins-core-man = %{version}-%{release}
Requires: dnf-plugins-core-python = %{version}-%{release}
Requires: dnf-plugins-core-python3 = %{version}-%{release}
BuildRequires : Flask
BuildRequires : Sphinx
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : binutils-dev
BuildRequires : binutils-extras
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : check-dev
BuildRequires : compat-lua-53
BuildRequires : compat-lua-53-abi
BuildRequires : compat-lua-53-bin
BuildRequires : compat-lua-53-dev
BuildRequires : compat-lua-53-lib
BuildRequires : compat-lua-53-man
BuildRequires : compat-lua-53-staticdev
BuildRequires : db-dev
BuildRequires : dbus-dev
BuildRequires : dbus-python
BuildRequires : dejagnu
BuildRequires : dnf
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : expect
BuildRequires : fakechroot
BuildRequires : fakechroot-dev
BuildRequires : fakechroot-staticdev
BuildRequires : file
BuildRequires : file-abi
BuildRequires : file-bin
BuildRequires : file-data
BuildRequires : file-dev
BuildRequires : file-lib
BuildRequires : file-license
BuildRequires : file-man
BuildRequires : flex
BuildRequires : gcc
BuildRequires : gcc-abi
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-doc
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdb
BuildRequires : gdb-dev
BuildRequires : gettext-bin
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : glibc-abi
BuildRequires : glibc-bench
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-doc
BuildRequires : glibc-extras
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : glibc-nscd
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnupg
BuildRequires : gpgme
BuildRequires : gpgme-dev
BuildRequires : graphviz
BuildRequires : guile
BuildRequires : json-c
BuildRequires : json-c-dev
BuildRequires : json-c-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libassuan-dev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcomps-dev
BuildRequires : libdnf
BuildRequires : libdnf-dev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libmodulemd
BuildRequires : libmodulemd-dev
BuildRequires : librepo-dev
BuildRequires : libsolv-dev
BuildRequires : libstdc++
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libunwind
BuildRequires : libunwind-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : m4
BuildRequires : nettle-dev
BuildRequires : nettle-staticdev
BuildRequires : nose
BuildRequires : nspr-dev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pluggy
BuildRequires : popt
BuildRequires : popt-dev
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : rpm
BuildRequires : rpm-dev
BuildRequires : sqlite-autoconf
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-staticdev
BuildRequires : swig
BuildRequires : tox
BuildRequires : unzip
BuildRequires : virtualenv
BuildRequires : xattr
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zip
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-fail-if-the-locklist-is-not-defined.patch
Patch2: 0002-sphinx-build-3-does-not-exist.patch

%description
Core Plugins for DNF. This package enhances DNF with builddep, config-manager,
copr, debug, debuginfo-install, download, needs-restarting, groups-manager, repoclosure,
repograph, repomanage, reposync, changelog and repodiff commands. Additionally
provides generate_completion_cache passive plugin.

%package libexec
Summary: libexec components for the dnf-plugins-core package.
Group: Default

%description libexec
libexec components for the dnf-plugins-core package.


%package locales
Summary: locales components for the dnf-plugins-core package.
Group: Default

%description locales
locales components for the dnf-plugins-core package.


%package man
Summary: man components for the dnf-plugins-core package.
Group: Default

%description man
man components for the dnf-plugins-core package.


%package python
Summary: python components for the dnf-plugins-core package.
Group: Default
Requires: dnf-plugins-core-python3 = %{version}-%{release}

%description python
python components for the dnf-plugins-core package.


%package python3
Summary: python3 components for the dnf-plugins-core package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dnf-plugins-core package.


%prep
%setup -q -n dnf-plugins-core-4.0.21
cd %{_builddir}/dnf-plugins-core-4.0.21
%patch1 -p1
%patch2 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618981679
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc"
#
export FCFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc"
export FFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer"
export CFFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc"
#
export LDFLAGS="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
%cmake .. -DPYTHON_DESIRED=3 -DWITH_MAN=0
make  %{?_smp_mflags}  ; make doc-man
popd

%install
export SOURCE_DATE_EPOCH=1618981679
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
%find_lang dnf-plugins-core

%files
%defattr(-,root,root,-)

%files libexec
%defattr(-,root,root,-)
/usr/libexec/dnf-utils-3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/debuginfo-install.1
/usr/share/man/man1/dnf-utils.1
/usr/share/man/man1/needs-restarting.1
/usr/share/man/man1/package-cleanup.1
/usr/share/man/man1/repo-graph.1
/usr/share/man/man1/repoclosure.1
/usr/share/man/man1/repodiff.1
/usr/share/man/man1/repomanage.1
/usr/share/man/man1/reposync.1
/usr/share/man/man1/yum-builddep.1
/usr/share/man/man1/yum-changelog.1
/usr/share/man/man1/yum-config-manager.1
/usr/share/man/man1/yum-debug-dump.1
/usr/share/man/man1/yum-debug-restore.1
/usr/share/man/man1/yum-groups-manager.1
/usr/share/man/man1/yum-utils.1
/usr/share/man/man1/yumdownloader.1
/usr/share/man/man5/yum-versionlock.conf.5
/usr/share/man/man8/dnf-builddep.8
/usr/share/man/man8/dnf-changelog.8
/usr/share/man/man8/dnf-config-manager.8
/usr/share/man/man8/dnf-copr.8
/usr/share/man/man8/dnf-debug.8
/usr/share/man/man8/dnf-debuginfo-install.8
/usr/share/man/man8/dnf-download.8
/usr/share/man/man8/dnf-generate_completion_cache.8
/usr/share/man/man8/dnf-groups-manager.8
/usr/share/man/man8/dnf-leaves.8
/usr/share/man/man8/dnf-local.8
/usr/share/man/man8/dnf-needs-restarting.8
/usr/share/man/man8/dnf-post-transaction-actions.8
/usr/share/man/man8/dnf-repoclosure.8
/usr/share/man/man8/dnf-repodiff.8
/usr/share/man/man8/dnf-repograph.8
/usr/share/man/man8/dnf-repomanage.8
/usr/share/man/man8/dnf-reposync.8
/usr/share/man/man8/dnf-show-leaves.8
/usr/share/man/man8/dnf-versionlock.8
/usr/share/man/man8/yum-copr.8
/usr/share/man/man8/yum-versionlock.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f dnf-plugins-core.lang
%defattr(-,root,root,-)

